/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BeatsRouteImport } from './routes/beats'
import { Route as BeatsIndexRouteImport } from './routes/beats/index'
import { Route as BeatsSlugRouteImport } from './routes/beats/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsRoute = BeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsIndexRoute = BeatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeatsRoute,
} as any)
const BeatsSlugRoute = BeatsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beats': typeof BeatsRouteWithChildren
  '/beats/$slug': typeof BeatsSlugRoute
  '/beats/': typeof BeatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beats/$slug': typeof BeatsSlugRoute
  '/beats': typeof BeatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/beats': typeof BeatsRouteWithChildren
  '/beats/$slug': typeof BeatsSlugRoute
  '/beats/': typeof BeatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/auth' | '/beats' | '/beats/$slug' | '/beats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/auth' | '/beats/$slug' | '/beats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/beats'
    | '/beats/$slug'
    | '/beats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BeatsRoute: typeof BeatsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats': {
      id: '/beats'
      path: '/beats'
      fullPath: '/beats'
      preLoaderRoute: typeof BeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats/': {
      id: '/beats/'
      path: '/'
      fullPath: '/beats/'
      preLoaderRoute: typeof BeatsIndexRouteImport
      parentRoute: typeof BeatsRoute
    }
    '/beats/$slug': {
      id: '/beats/$slug'
      path: '/$slug'
      fullPath: '/beats/$slug'
      preLoaderRoute: typeof BeatsSlugRouteImport
      parentRoute: typeof BeatsRoute
    }
  }
}

interface BeatsRouteChildren {
  BeatsSlugRoute: typeof BeatsSlugRoute
  BeatsIndexRoute: typeof BeatsIndexRoute
}

const BeatsRouteChildren: BeatsRouteChildren = {
  BeatsSlugRoute: BeatsSlugRoute,
  BeatsIndexRoute: BeatsIndexRoute,
}

const BeatsRouteWithChildren = BeatsRoute._addFileChildren(BeatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BeatsRoute: BeatsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
